#!/usr/bin/env bash
set -euo pipefail

MAPRED_NUM_REDUCE_TASKS_SET=(1 3 5 10 15 20)
SPLIT_MINSIZE_SET=(1024 2048 8192 32768 131072 262144)

for MAPRED_NUM_REDUCE_TASKS in "${MAPRED_NUM_REDUCE_TASKS_SET[@]}"; do
  for SPLIT_MINSIZE in "${SPLIT_MINSIZE_SET[@]}"; do
    echo "Running with MAPRED_NUM_REDUCE_TASKS=$MAPRED_NUM_REDUCE_TASKS SPLIT_MINSIZE=$SPLIT_MINSIZE"
    MAPRED_NUM_REDUCE_TASKS="$MAPRED_NUM_REDUCE_TASKS" SPLIT_MINSIZE="$SPLIT_MINSIZE" docker compose up --build
    docker compose down --volumes --remove-orphans || true
  done
done
